### ISSUE TITLE
Add sender to resolver UID

### ISSUE THREAD

**Issue by kopy-kat** [rhinestonewtf/registry#51]
Not using the sender/owner to calculate the UID of Resolvers could lead to senders being frontrun and unable to register the Resolver because the UID is already taken - it could also lead to resolvers being owned by someone malicious without noticing and later changed (thanks to Lee Yu for pointing this out)

**Comment by kanthgithub** [comment]
this one seems to be already implemented in [Helpers.sol](https://github.com/rhinestonewtf/registry/blob/main/src/lib/Helpers.sol#L26)
can be marked closed?

**Comment by kopy-kat** [comment]
yep, thanks for pointing this out!
