### ISSUE TITLE
RegisterResolver function - Rename Modifier onlyResolver to isSupportedResolver

### ISSUE THREAD

**Issue by kanthgithub** [rhinestonewtf/registry#60]
## Background
- [registerResolver](https://github.com/rhinestonewtf/registry/blob/main/src/core/ResolverManager.sol#L84-L100) function has a modifier called [onlyResolver](https://github.com/rhinestonewtf/registry/blob/main/src/core/ResolverManager.sol#L74-L79) 
- it checks if the resolver address is not zero address and supports the interface for IExternalResolver

## Minor readability Issue
- name `onlyResolver` may mean if it is checking the address is a resolver address
- sounds similar to `onlyOwner` 

## Suggested change
- rename `onlyResolver` to `isSupportedResolver`

**Comment by zeroknots** [comment]
dont think this is a relevant enough change.
