### ISSUE TITLE
calculation of schema UIDs

### ISSUE THREAD

**Issue by zeroknots** [rhinestonewtf/registry#7]
we are currently deriving the schemaUID by calculating a hash on the schema string, the owner (wallet registering the schema) and if its revokable.

I am not sure if this is a good derivation path...

we need schemaIDs to be the same across chains to allow for propagation, and the schema need to be bound to the creator, or else someone could frontrun registration and block the schemaID.  

the downside of the current derivation path is that it doesnt allow for wallet rotation for authorities in the future.

we could use the resolver address as a parameter in the hash derivation but that also makes things dangerous if some authorities choose to use create2 for their resolver and can be frontrun 

https://github.com/rhinestonewtf/registry/blob/main/src/base/RSSchema.sol#L110-L121

**Comment by kanthgithub** [comment]
here is this linked to https://github.com/rhinestonewtf/registry/issues/51 ?
where the UID calculation should include sender/owner to avoid front running?
@zeroknots @kopy-kat
